# docker-compose.yml
version: '3.8' # Specify the Docker Compose file format version

services:
  vera-rag:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      # Mount the local 'data' directory
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    restart: unless-stopped